@startuml
skinparam defaultFontName Arial

start
if (head is empty?) then (yes)
  :head = Node(value);
  stop
else (no)
  :current = head;
  while (current has next_node?) is (yes)
    :current = current.next_node;
  endwhile (no)
  :current.next_node = Node(value);
  stop
endif
@enduml
