@startuml
start
if (self.head is null?) then (yes)
  :return;
else (no)
  if (self.head.value == value?) then (yes)
    :self.head = self.head.next_node;
    stop
  else (no)
    :current = self.head;
    while (current.next_node is not null?)
      if (current.next_node.value == value?) then (yes)
        :current.next_node = current.next_node.next_node;
        stop
      else (no)
        :current = current.next_node;
      endif
    endwhile
  endif
endif
@enduml
