@startuml
start
:current = self.head;
while (current?) is (true)
    if (current.value == value) then (yes)
        :return current;
    else (no)
        :current = current.next_node;
    endif
endwhile (no)
:return None;
stop
@enduml
