@startuml

start
:current = self.head;
:index = 0;
while (current) is (true)
    if (func(current)) then (true)
        :return index;
    elseif (func(current)) then (false)
        :index += 1;
        :current = current.next_node;
    else (no current)
        :return -1;
    endif
endwhile
@enduml
