@startuml

start
:Initialize start node;
:Mark distance of start node as 0;
:Create list of unvisited nodes with distances;
:Initialize list for minimum spanning tree edges;
while (unvisited nodes exist?) is (yes)
    :Choose node with shortest distance;
    :Mark node as visited;
    if (node has previous node) then (yes)
        :Add edge to minimum spanning tree;
    endif
    while (unvisited neighbors exist?) is (yes)
        :Update distances to neighbors if shorter;
    endwhile
endwhile
:Return minimum spanning tree edges;
stop

@enduml
